<a href="https://colab.research.google.com/github/cristianmunoz1/ai4eng-proyecto/blob/main/05%20-%20preprocesado%20con%20departamento%20de%20test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Replicamos los recursos locales en el entorno virtual

### Descargamos los datos de la competencia al entorno de trabajo

In [ ]:
import os
os.environ['KAGGLE_CONFIG_DIR'] = '.'
!chmod 600 ./kaggle.json
!kaggle competitions download -c udea-ai4eng-20242

Downloading udea-ai4eng-20242.zip to /content
 45% 9.00M/20.1M [00:00<00:00, 78.7MB/s]
100% 20.1M/20.1M [00:00<00:00, 118MB/s]

### Descomprimimos el archivo

In [ ]:
!unzip udea*.zip > /dev/null

In [ ]:
!wc *.csv

   296787    296787   4716673 submission_example.csv
   296787   4565553  50135751 test.csv
   692501  10666231 118025055 train.csv
  1286075  15528571 172877479 total

## Importe de librerías necesarias

Se importan las librerías necesarias tales como:

- Pandas: Para la manipulación y análisis de datos con los DataFrames.
- Numpy: Para los cálculos matemáticos y el manejo eficiente de los arrays.
- Unidecode: Para normalizar el texto eliminado caracteres especiales o acentos.
- sklearn.preprocessing: Para convertir datos categóricos en un formato que nos sea de mayor utilidad.

In [ ]:
!pip install unidecode

Requirement already satisfied: unidecode in /usr/local/lib/python3.10/dist-packages (1.3.8)

In [ ]:
import unidecode as ud
import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

### Cargamos el csv como un dataframe de Pandas
Guardamos el cvs en la variable test e imprimimos la cantidad de filas y columnas del DataFrame test.

In [ ]:
test = pd.read_csv("test.csv")
print ("shape of loaded dataframe", test.shape)

shape of loaded dataframe (296786, 12)

Visualizamos las columnas del DataFrame test.

In [ ]:
test.columns

Index(['Unnamed: 0', 'ID', 'PERIODO', 'ESTU_PRGM_ACADEMICO',
       'ESTU_PRGM_DEPARTAMENTO', 'ESTU_VALORMATRICULAUNIVERSIDAD',
       'ESTU_HORASSEMANATRABAJA', 'FAMI_ESTRATOVIVIENDA', 'FAMI_TIENEINTERNET',
       'FAMI_EDUCACIONPADRE', 'FAMI_EDUCACIONMADRE',
       'ESTU_PAGOMATRICULAPROPIO'],
      dtype='object')

Generamos una vista inicial de los datos.

In [ ]:
test.head()

,Unnamed: 0,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,ESTU_PAGOMATRICULAPROPIO
0,0,550236,20183,TRABAJO SOCIAL,BOLIVAR,Menos de 500 mil,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica completa,Primaria completa,Si
1,1,98545,20203,ADMINISTRACION COMERCIAL Y DE MERCADEO,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Técnica o tecnológica completa,No
2,2,499179,20212,INGENIERIA MECATRONICA,BOGOTÁ,Entre 1 millón y menos de 2.5 millones,0,Estrato 3,Si,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) completa,No
3,3,782980,20195,CONTADURIA PUBLICA,SUCRE,Entre 1 millón y menos de 2.5 millones,Entre 21 y 30 horas,Estrato 1,No,Primaria incompleta,Primaria incompleta,No
4,4,785185,20212,ADMINISTRACION DE EMPRESAS,ATLANTICO,Entre 2.5 millones y menos de 4 millones,Entre 11 y 20 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,No

## One_hot encoding para la columna 'ESTU_PRGMACADEMICO'

Estrategia de preprocesado de 'ESTU_PRGM_ACADEMICO'
- Observamos cuantas carreras únicas hay y cuales de estas son.
- Las pasamos todas a minúsculas para que se agrupen algunas que eran las mismas pero escritas con diferentes combinaciones de mayúsculas y minúsculas.
- Dejamos en un array de numpy solo las carreras que tengan más de 6000 apariciones en el Dataframe original. Con el objetivo de agrupar al rededor de 20 carreras diferentes.
- A las demás carreras las agrupamos en un grupo 'otros' con el objetivo de reducir el ruido en los datos y la posible variabilidad que puedan presentar.
- Aplicamos OneHotEncoding a los nuevos datos en la columna.

In [ ]:
carreras_unicas = test['ESTU_PRGM_ACADEMICO'].unique()

In [ ]:
test['ESTU_PRGM_ACADEMICO'] = test['ESTU_PRGM_ACADEMICO'].apply(lambda x: ud.unidecode(x.lower()))

In [ ]:
test.head()

,Unnamed: 0,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,ESTU_PAGOMATRICULAPROPIO
0,0,550236,20183,trabajo social,BOLIVAR,Menos de 500 mil,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica completa,Primaria completa,Si
1,1,98545,20203,administracion comercial y de mercadeo,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Técnica o tecnológica completa,No
2,2,499179,20212,ingenieria mecatronica,BOGOTÁ,Entre 1 millón y menos de 2.5 millones,0,Estrato 3,Si,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) completa,No
3,3,782980,20195,contaduria publica,SUCRE,Entre 1 millón y menos de 2.5 millones,Entre 21 y 30 horas,Estrato 1,No,Primaria incompleta,Primaria incompleta,No
4,4,785185,20212,administracion de empresas,ATLANTICO,Entre 2.5 millones y menos de 4 millones,Entre 11 y 20 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,No

In [ ]:
prgm_acads = ['administracion de empresas', 'derecho', 'contaduria publica',
       'psicologia', 'ingenieria industrial', 'ingenieria civil', 'medicina',
       'ingenieria de sistemas', 'licenciatura en pedagogia infantil',
       'ingenieria ambiental', 'trabajo social', 'enfermeria', 'arquitectura',
       'administracion en salud ocupacional', 'negocios internacionales',
       'economia', 'ingenieria mecanica', 'ingenieria electronica',
       'comunicacion social', 'administracion financiera']
len(prgm_acads)

20

In [ ]:
array = [element for element in test['ESTU_PRGM_ACADEMICO'] if element not in prgm_acads ]
array

condition = test['ESTU_PRGM_ACADEMICO'].isin(array)
test.loc[condition, 'ESTU_PRGM_ACADEMICO'] = "otros"
test.head()

,Unnamed: 0,ID,PERIODO,ESTU_PRGM_ACADEMICO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,ESTU_PAGOMATRICULAPROPIO
0,0,550236,20183,trabajo social,BOLIVAR,Menos de 500 mil,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica completa,Primaria completa,Si
1,1,98545,20203,otros,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Técnica o tecnológica completa,No
2,2,499179,20212,otros,BOGOTÁ,Entre 1 millón y menos de 2.5 millones,0,Estrato 3,Si,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) completa,No
3,3,782980,20195,contaduria publica,SUCRE,Entre 1 millón y menos de 2.5 millones,Entre 21 y 30 horas,Estrato 1,No,Primaria incompleta,Primaria incompleta,No
4,4,785185,20212,administracion de empresas,ATLANTICO,Entre 2.5 millones y menos de 4 millones,Entre 11 y 20 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,No

In [ ]:
test['ESTU_PRGM_ACADEMICO'].value_counts()

ESTU_PRGM_ACADEMICO
otros                                  107041
administracion de empresas              33008
derecho                                 22984
contaduria publica                      22103
psicologia                              21256
ingenieria industrial                   15228
ingenieria civil                         9079
medicina                                 7915
ingenieria de sistemas                   7655
licenciatura en pedagogia infantil       6323
ingenieria ambiental                     5719
trabajo social                           5286
enfermeria                               5223
arquitectura                             4851
administracion en salud ocupacional      4690
negocios internacionales                 3787
economia                                 3158
ingenieria mecanica                      3037
ingenieria electronica                   2969
administracion financiera                2803
comunicacion social                      2671
Name: count, dtype: int64

In [ ]:
encode = OneHotEncoder()

codificadorPrg = encode.fit_transform(test[['ESTU_PRGM_ACADEMICO']])

arreglo = pd.DataFrame(codificadorPrg.toarray(), columns = encode.categories_)
print(arreglo)
test.drop('ESTU_PRGM_ACADEMICO', axis = 1)

test = pd.concat([test, arreglo], axis = 'columns')
test['ESTU_PRGM_ACADEMICO']

       administracion de empresas administracion en salud ocupacional  \
0                             0.0                                 0.0
1                             0.0                                 0.0
2                             0.0                                 0.0
3                             0.0                                 0.0
4                             1.0                                 0.0
...                           ...                                 ...
296781                        1.0                                 0.0
296782                        0.0                                 0.0
296783                        0.0                                 0.0
296784                        0.0                                 0.0
296785                        0.0                                 0.0

       administracion financiera arquitectura comunicacion social  \
0                            0.0          0.0                 0.0
1                            0.0          0.0                 0.0
2                            0.0          0.0                 0.0
3                            0.0          0.0                 0.0
4                            0.0          0.0                 0.0
...                          ...          ...                 ...
296781                       0.0          0.0                 0.0
296782                       0.0          0.0                 0.0
296783                       0.0          0.0                 0.0
296784                       0.0          0.0                 0.0
296785                       0.0          0.0                 0.0

       contaduria publica derecho economia enfermeria ingenieria ambiental  \
0                     0.0     0.0      0.0        0.0                  0.0
1                     0.0     0.0      0.0        0.0                  0.0
2                     0.0     0.0      0.0        0.0                  0.0
3                     1.0     0.0      0.0        0.0                  0.0
4                     0.0     0.0      0.0        0.0                  0.0
...                   ...     ...      ...        ...                  ...
296781                0.0     0.0      0.0        0.0                  0.0
296782                0.0     1.0      0.0        0.0                  0.0
296783                0.0     1.0      0.0        0.0                  0.0
296784                0.0     0.0      0.0        0.0                  0.0
296785                0.0     0.0      0.0        0.0                  0.0

        ... ingenieria de sistemas ingenieria electronica  \
0       ...                    0.0                    0.0
1       ...                    0.0                    0.0
2       ...                    0.0                    0.0
3       ...                    0.0                    0.0
4       ...                    0.0                    0.0
...     ...                    ...                    ...
296781  ...                    0.0                    0.0
296782  ...                    0.0                    0.0
296783  ...                    0.0                    0.0
296784  ...                    0.0                    0.0
296785  ...                    0.0                    0.0

       ingenieria industrial ingenieria mecanica  \
0                        0.0                 0.0
1                        0.0                 0.0
2                        0.0                 0.0
3                        0.0                 0.0
4                        0.0                 0.0
...                      ...                 ...
296781                   0.0                 0.0
296782                   0.0                 0.0
296783                   0.0                 0.0
296784                   0.0                 0.0
296785                   1.0                 0.0

       licenciatura en pedagogia infantil medicina negocios internacionales  \
0                                     0.0      0.0                      0.0
1                                     0.0      0.0                      0.0
2                                     0.0      0.0                      0.0
3                                     0.0      0.0                      0.0
4                                     0.0      0.0                      0.0
...                                   ...      ...                      ...
296781                                0.0      0.0                      0.0
296782                                0.0      0.0                      0.0
296783                                0.0      0.0                      0.0
296784                                0.0      0.0                      0.0
296785                                0.0      0.0                      0.0

       otros psicologia trabajo social
0        0.0        0.0            1.0
1        1.0        0.0            0.0
2        1.0        0.0            0.0
3        0.0        0.0            0.0
4        0.0        0.0            0.0
...      ...        ...            ...
296781   0.0        0.0            0.0
296782   0.0        0.0            0.0
296783   0.0        0.0            0.0
296784   1.0        0.0            0.0
296785   0.0        0.0            0.0

[296786 rows x 21 columns]

0                     trabajo social
1                              otros
2                              otros
3                 contaduria publica
4         administracion de empresas
                     ...
296781    administracion de empresas
296782                       derecho
296783                       derecho
296784                         otros
296785         ingenieria industrial
Name: ESTU_PRGM_ACADEMICO, Length: 296786, dtype: object

In [ ]:
test = test.drop('ESTU_PRGM_ACADEMICO', axis = 1)

In [ ]:
test.head()

,Unnamed: 0,ID,PERIODO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,...,"(ingenieria de sistemas,)","(ingenieria electronica,)","(ingenieria industrial,)","(ingenieria mecanica,)","(licenciatura en pedagogia infantil,)","(medicina,)","(negocios internacionales,)","(otros,)","(psicologia,)","(trabajo social,)"
0,0,550236,20183,BOLIVAR,Menos de 500 mil,Menos de 10 horas,Estrato 3,Si,Técnica o tecnológica completa,Primaria completa,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1,98545,20203,ANTIOQUIA,Entre 2.5 millones y menos de 4 millones,Entre 21 y 30 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Técnica o tecnológica completa,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,2,499179,20212,BOGOTÁ,Entre 1 millón y menos de 2.5 millones,0,Estrato 3,Si,Secundaria (Bachillerato) incompleta,Secundaria (Bachillerato) completa,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,3,782980,20195,SUCRE,Entre 1 millón y menos de 2.5 millones,Entre 21 y 30 horas,Estrato 1,No,Primaria incompleta,Primaria incompleta,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,785185,20212,ATLANTICO,Entre 2.5 millones y menos de 4 millones,Entre 11 y 20 horas,Estrato 2,Si,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
test.columns

Index([                            'Unnamed: 0',
                                           'ID',
                                      'PERIODO',
                       'ESTU_PRGM_DEPARTAMENTO',
               'ESTU_VALORMATRICULAUNIVERSIDAD',
                      'ESTU_HORASSEMANATRABAJA',
                         'FAMI_ESTRATOVIVIENDA',
                           'FAMI_TIENEINTERNET',
                          'FAMI_EDUCACIONPADRE',
                          'FAMI_EDUCACIONMADRE',
                     'ESTU_PAGOMATRICULAPROPIO',
                ('administracion de empresas',),
       ('administracion en salud ocupacional',),
                 ('administracion financiera',),
                              ('arquitectura',),
                       ('comunicacion social',),
                        ('contaduria publica',),
                                   ('derecho',),
                                  ('economia',),
                                ('enfermeria',),
                      ('ingenieria ambiental',),
                          ('ingenieria civil',),
                    ('ingenieria de sistemas',),
                    ('ingenieria electronica',),
                     ('ingenieria industrial',),
                       ('ingenieria mecanica',),
        ('licenciatura en pedagogia infantil',),
                                  ('medicina',),
                  ('negocios internacionales',),
                                     ('otros',),
                                ('psicologia',),
                            ('trabajo social',)],
      dtype='object')

In [ ]:
test = test.drop('Unnamed: 0', axis = 1)

## Categorización ordinal de las columnas categóricas ordinales

Decidimos convertir las variables categóricas que tienen un orden natural en un formato número para facilitar su procesamiento.

In [ ]:
test.columns

Index([                                    'ID',
                                      'PERIODO',
                       'ESTU_PRGM_DEPARTAMENTO',
               'ESTU_VALORMATRICULAUNIVERSIDAD',
                      'ESTU_HORASSEMANATRABAJA',
                         'FAMI_ESTRATOVIVIENDA',
                           'FAMI_TIENEINTERNET',
                          'FAMI_EDUCACIONPADRE',
                          'FAMI_EDUCACIONMADRE',
                     'ESTU_PAGOMATRICULAPROPIO',
                ('administracion de empresas',),
       ('administracion en salud ocupacional',),
                 ('administracion financiera',),
                              ('arquitectura',),
                       ('comunicacion social',),
                        ('contaduria publica',),
                                   ('derecho',),
                                  ('economia',),
                                ('enfermeria',),
                      ('ingenieria ambiental',),
                          ('ingenieria civil',),
                    ('ingenieria de sistemas',),
                    ('ingenieria electronica',),
                     ('ingenieria industrial',),
                       ('ingenieria mecanica',),
        ('licenciatura en pedagogia infantil',),
                                  ('medicina',),
                  ('negocios internacionales',),
                                     ('otros',),
                                ('psicologia',),
                            ('trabajo social',)],
      dtype='object')

## Quitarle los valores nulos a todas las columnas categóricas ordinales

### Conteo de valores nulos

Realizamos un conteo para saber cuantos valores nulos hay en algunas columnas específicas:

In [ ]:
test['FAMI_EDUCACIONMADRE'].value_counts()

FAMI_EDUCACIONMADRE
Secundaria (Bachillerato) completa      60649
Primaria incompleta                     42149
Técnica o tecnológica completa          38571
Educación profesional completa          36477
Secundaria (Bachillerato) incompleta    34566
Primaria completa                       24399
Postgrado                               20049
Técnica o tecnológica incompleta        11650
Educación profesional incompleta         9647
Ninguno                                  6335
No sabe                                  1286
No Aplica                                 785
Name: count, dtype: int64

In [ ]:
print(f"Cantidad nulos valor matrícula = {test['ESTU_VALORMATRICULAUNIVERSIDAD'].isna().sum()}")
print(f"Cantidad nulos horas semanales trabaja = {test['ESTU_HORASSEMANATRABAJA'].isna().sum()}")
print(f"Cantidad nulos estrato vivienda = {test['FAMI_ESTRATOVIVIENDA'].isna().sum()}")
print(f"Cantidad nulos educación padre = {test['FAMI_EDUCACIONPADRE'].isna().sum()}")
print(f"Cantidad nulos educación madre = {test['FAMI_EDUCACIONMADRE'].isna().sum()}")

Cantidad nulos valor matrícula = 2723
Cantidad nulos horas semanales trabaja = 13379
Cantidad nulos estrato vivienda = 13795
Cantidad nulos educación padre = 9993
Cantidad nulos educación madre = 10223

### Cambio de valores nulos por 'no info'

Realizamos este proceso con el fin de no perder información, indicar ausencia de datos y evitar sesgos conservando la distinción de que falta información.

In [ ]:
test['ESTU_VALORMATRICULAUNIVERSIDAD'] = test['ESTU_VALORMATRICULAUNIVERSIDAD'].fillna("no info")
test['ESTU_HORASSEMANATRABAJA'] = test['ESTU_HORASSEMANATRABAJA'].fillna("no info")
test['FAMI_ESTRATOVIVIENDA'] = test['FAMI_ESTRATOVIVIENDA'].fillna("no info")
test['FAMI_EDUCACIONPADRE'] = test['FAMI_EDUCACIONPADRE'].fillna("no info")
test['FAMI_EDUCACIONMADRE'] = test['FAMI_EDUCACIONMADRE'].fillna("no info")

## Codificación de valores categóricos ordinales.

Se define un conjunto de categorías para cada una de las columnas categóricas ordinales en el DataFrame con un orden lógico para transformar las columnas en valores numéricos, lo cuál es necesario para realizar nuestro modelo.

In [ ]:
categories = [
    ['no info', 'No pagó matrícula', 'Menos de 500 mil', 'Entre 500 mil y menos de 1 millón',
     'Entre 1 millón y menos de 2.5 millones', 'Entre 2.5 millones y menos de 4 millones',
     'Entre 4 millones y menos de 5.5 millones', 'Entre 5.5 millones y menos de 7 millones',
     'Más de 7 millones'],  # ESTU_VALORMATRICULAUNIVERSIDAD
    ['no info', '0', 'Menos de 10 horas', 'Entre 11 y 20 horas', 'Entre 21 y 30 horas', 'Más de 30 horas'],  # ESTU_HORASSEMANATRABAJA
    ['no info', 'Sin Estrato', 'Estrato 1', 'Estrato 2', 'Estrato 3', 'Estrato 4', 'Estrato 5', 'Estrato 6'],  # FAMI_ESTRATOVIVIENDA
    ['no info', 'Ninguno', 'No sabe', 'No Aplica', 'Primaria incompleta', 'Primaria completa',
     'Secundaria (Bachillerato) incompleta', 'Secundaria (Bachillerato) completa', 'Técnica o tecnológica incompleta',
     'Técnica o tecnológica completa', 'Educación profesional incompleta', 'Educación profesional completa', 'Postgrado'],  # FAMI_EDUCACIONPADRE
    ['no info', 'Ninguno', 'No sabe', 'No Aplica', 'Primaria incompleta', 'Primaria completa',
     'Secundaria (Bachillerato) incompleta', 'Secundaria (Bachillerato) completa', 'Técnica o tecnológica incompleta',
     'Técnica o tecnológica completa', 'Educación profesional incompleta', 'Educación profesional completa', 'Postgrado'],  # FAMI_EDUCACIONMADRE
]

Utilizamos OrdinalEncoder de Scikitlearn para que a cada categoría dentro de la columna se le asigne un valor numperivo basado en el orden que se definió en el paso anterior.

In [ ]:
codificador = OrdinalEncoder(categories=categories)
test[['ESTU_VALORMATRICULAUNIVERSIDAD', 'ESTU_HORASSEMANATRABAJA',
       'FAMI_ESTRATOVIVIENDA', 'FAMI_EDUCACIONPADRE',
       'FAMI_EDUCACIONMADRE']] = codificador.fit_transform(
    test[['ESTU_VALORMATRICULAUNIVERSIDAD', 'ESTU_HORASSEMANATRABAJA',
           'FAMI_ESTRATOVIVIENDA', 'FAMI_EDUCACIONPADRE',
           'FAMI_EDUCACIONMADRE']]
       )

In [ ]:
test.head()

,ID,PERIODO,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_TIENEINTERNET,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,ESTU_PAGOMATRICULAPROPIO,...,"(ingenieria de sistemas,)","(ingenieria electronica,)","(ingenieria industrial,)","(ingenieria mecanica,)","(licenciatura en pedagogia infantil,)","(medicina,)","(negocios internacionales,)","(otros,)","(psicologia,)","(trabajo social,)"
0,550236,20183,BOLIVAR,2.0,2.0,4.0,Si,9.0,5.0,Si,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,98545,20203,ANTIOQUIA,5.0,4.0,3.0,Si,7.0,9.0,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,499179,20212,BOGOTÁ,4.0,1.0,4.0,Si,6.0,7.0,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,782980,20195,SUCRE,4.0,4.0,2.0,No,4.0,4.0,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,785185,20212,ATLANTICO,5.0,3.0,3.0,Si,7.0,7.0,No,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
test.columns

Index([                                    'ID',
                                      'PERIODO',
                       'ESTU_PRGM_DEPARTAMENTO',
               'ESTU_VALORMATRICULAUNIVERSIDAD',
                      'ESTU_HORASSEMANATRABAJA',
                         'FAMI_ESTRATOVIVIENDA',
                           'FAMI_TIENEINTERNET',
                          'FAMI_EDUCACIONPADRE',
                          'FAMI_EDUCACIONMADRE',
                     'ESTU_PAGOMATRICULAPROPIO',
                ('administracion de empresas',),
       ('administracion en salud ocupacional',),
                 ('administracion financiera',),
                              ('arquitectura',),
                       ('comunicacion social',),
                        ('contaduria publica',),
                                   ('derecho',),
                                  ('economia',),
                                ('enfermeria',),
                      ('ingenieria ambiental',),
                          ('ingenieria civil',),
                    ('ingenieria de sistemas',),
                    ('ingenieria electronica',),
                     ('ingenieria industrial',),
                       ('ingenieria mecanica',),
        ('licenciatura en pedagogia infantil',),
                                  ('medicina',),
                  ('negocios internacionales',),
                                     ('otros',),
                                ('psicologia',),
                            ('trabajo social',)],
      dtype='object')

Reemplazamos los valores nulos de la columna con el valor no info.

In [ ]:
test['ESTU_PAGOMATRICULAPROPIO'] = test['ESTU_PAGOMATRICULAPROPIO'].fillna('no info')
test['ESTU_PAGOMATRICULAPROPIO'].value_counts()

ESTU_PAGOMATRICULAPROPIO
No         163869
Si         130110
no info      2807
Name: count, dtype: int64

In [ ]:
print(f"Cantidad nulos tiene internet = {test['ESTU_PAGOMATRICULAPROPIO'].isna().sum()}")
test['FAMI_TIENEINTERNET'].value_counts()

Cantidad nulos tiene internet = 0

FAMI_TIENEINTERNET
Si    254075
No     31172
Name: count, dtype: int64

## Conversión One-Hot de las columnas FAMI_TIENEINTERNET y ESTU_PAGOMATRICULAPROPIO

Preparamos los datos para hacer el uso del modelo con un one-hot.

In [ ]:
one_hot_encoded = pd.get_dummies(test['ESTU_PAGOMATRICULAPROPIO'], prefix = 'ESTU_PAGOMATRICULAPROPIO')
one_hot_encoded = one_hot_encoded.astype(int)
one_hot_encoded

,ESTU_PAGOMATRICULAPROPIO_No,ESTU_PAGOMATRICULAPROPIO_Si,ESTU_PAGOMATRICULAPROPIO_no info
0,0,1,0
1,1,0,0
2,1,0,0
3,1,0,0
4,1,0,0
...,...,...,...
296781,0,1,0
296782,1,0,0
296783,1,0,0
296784,1,0,0
296785,1,0,0

In [ ]:
test = pd.concat([test, one_hot_encoded], axis = 1)
test = test.drop('ESTU_PAGOMATRICULAPROPIO', axis = 1)

In [ ]:
test['ESTU_PAGOMATRICULAPROPIO_No'].head()

0    0
1    1
2    1
3    1
4    1
Name: ESTU_PAGOMATRICULAPROPIO_No, dtype: int64

In [ ]:
print(test.columns)

Index([                                    'ID',
                                      'PERIODO',
                       'ESTU_PRGM_DEPARTAMENTO',
               'ESTU_VALORMATRICULAUNIVERSIDAD',
                      'ESTU_HORASSEMANATRABAJA',
                         'FAMI_ESTRATOVIVIENDA',
                           'FAMI_TIENEINTERNET',
                          'FAMI_EDUCACIONPADRE',
                          'FAMI_EDUCACIONMADRE',
                ('administracion de empresas',),
       ('administracion en salud ocupacional',),
                 ('administracion financiera',),
                              ('arquitectura',),
                       ('comunicacion social',),
                        ('contaduria publica',),
                                   ('derecho',),
                                  ('economia',),
                                ('enfermeria',),
                      ('ingenieria ambiental',),
                          ('ingenieria civil',),
                    ('ingenieria de sistemas',),
                    ('ingenieria electronica',),
                     ('ingenieria industrial',),
                       ('ingenieria mecanica',),
        ('licenciatura en pedagogia infantil',),
                                  ('medicina',),
                  ('negocios internacionales',),
                                     ('otros',),
                                ('psicologia',),
                            ('trabajo social',),
                  'ESTU_PAGOMATRICULAPROPIO_No',
                  'ESTU_PAGOMATRICULAPROPIO_Si',
             'ESTU_PAGOMATRICULAPROPIO_no info'],
      dtype='object')

In [ ]:
one_hot_encoded = pd.get_dummies(test['FAMI_TIENEINTERNET'], prefix = 'FAMI_TIENEINTERNET')
one_hot_encoded = one_hot_encoded.astype(int)
one_hot_encoded

        FAMI_TIENEINTERNET_No  FAMI_TIENEINTERNET_Si
0                           0                      1
1                           0                      1
2                           0                      1
3                           1                      0
4                           0                      1
...                       ...                    ...
296781                      0                      1
296782                      0                      1
296783                      0                      1
296784                      0                      1
296785                      0                      1

[296786 rows x 2 columns]

Concatenamos las columnas One-hot al DataFrame original y eliminamos la columna original ya que no es necesaria, y así evitamos redundancia en el conjunto de datos

In [ ]:
test = pd.concat([test, one_hot_encoded], axis = 1)
test = test.drop('FAMI_TIENEINTERNET', axis = 1)

Finalmente, realizamos una inspeccion y revision de las nuevas columnas generadas.

In [ ]:
test['FAMI_TIENEINTERNET_Si'].head()

0    1
1    1
2    1
3    0
4    1
Name: FAMI_TIENEINTERNET_Si, dtype: int64

### Eliminamos la columna de departamento para no tenerla en cuenta para este preprocesado

Decidimos agrupar los departamentos en categorías de 'ricos' y 'pobres', ya que creemos que esta clasificación tiene un impacto en el desempeño de los estudiantes. Las condiciones socioeconómicas de cada región influyen significativamente en el tipo de educación que reciben los estudiantes, lo que a su vez puede afectar sus resultados académicos. Dividimos los departamentos según información proporcionada por el DANE.

In [ ]:
richest_deps = ['BOGOTÁ', 'RISARALDA', 'SANTANDER', 'ANTIOQUIA', 'CALDAS', 'CUNDINAMARCA', 'META', 'VALLE', 'QUINDIO', 'ATLANTICO', 'BOYACA']

In [ ]:
test.columns

Index([                                    'ID',
                                      'PERIODO',
                       'ESTU_PRGM_DEPARTAMENTO',
               'ESTU_VALORMATRICULAUNIVERSIDAD',
                      'ESTU_HORASSEMANATRABAJA',
                         'FAMI_ESTRATOVIVIENDA',
                          'FAMI_EDUCACIONPADRE',
                          'FAMI_EDUCACIONMADRE',
                ('administracion de empresas',),
       ('administracion en salud ocupacional',),
                 ('administracion financiera',),
                              ('arquitectura',),
                       ('comunicacion social',),
                        ('contaduria publica',),
                                   ('derecho',),
                                  ('economia',),
                                ('enfermeria',),
                      ('ingenieria ambiental',),
                          ('ingenieria civil',),
                    ('ingenieria de sistemas',),
                    ('ingenieria electronica',),
                     ('ingenieria industrial',),
                       ('ingenieria mecanica',),
        ('licenciatura en pedagogia infantil',),
                                  ('medicina',),
                  ('negocios internacionales',),
                                     ('otros',),
                                ('psicologia',),
                            ('trabajo social',),
                  'ESTU_PAGOMATRICULAPROPIO_No',
                  'ESTU_PAGOMATRICULAPROPIO_Si',
             'ESTU_PAGOMATRICULAPROPIO_no info',
                        'FAMI_TIENEINTERNET_No',
                        'FAMI_TIENEINTERNET_Si'],
      dtype='object')

In [ ]:
test['ESTU_PRGM_DEPARTAMENTO'] = test['ESTU_PRGM_DEPARTAMENTO'].apply(lambda x: 1 if x in richest_deps else 0)

In [ ]:
test['ESTU_PRGM_DEPARTAMENTO'].values

array([0, 1, 1, ..., 1, 1, 1])

In [ ]:
test.columns

Index([                                    'ID',
                                      'PERIODO',
                       'ESTU_PRGM_DEPARTAMENTO',
               'ESTU_VALORMATRICULAUNIVERSIDAD',
                      'ESTU_HORASSEMANATRABAJA',
                         'FAMI_ESTRATOVIVIENDA',
                          'FAMI_EDUCACIONPADRE',
                          'FAMI_EDUCACIONMADRE',
                ('administracion de empresas',),
       ('administracion en salud ocupacional',),
                 ('administracion financiera',),
                              ('arquitectura',),
                       ('comunicacion social',),
                        ('contaduria publica',),
                                   ('derecho',),
                                  ('economia',),
                                ('enfermeria',),
                      ('ingenieria ambiental',),
                          ('ingenieria civil',),
                    ('ingenieria de sistemas',),
                    ('ingenieria electronica',),
                     ('ingenieria industrial',),
                       ('ingenieria mecanica',),
        ('licenciatura en pedagogia infantil',),
                                  ('medicina',),
                  ('negocios internacionales',),
                                     ('otros',),
                                ('psicologia',),
                            ('trabajo social',),
                  'ESTU_PAGOMATRICULAPROPIO_No',
                  'ESTU_PAGOMATRICULAPROPIO_Si',
             'ESTU_PAGOMATRICULAPROPIO_no info',
                        'FAMI_TIENEINTERNET_No',
                        'FAMI_TIENEINTERNET_Si'],
      dtype='object')

### Eliminamos la columna periodo y ID ya que se considera, no tiene efecto sobre el rendimiento

In [ ]:
test = test.drop('PERIODO', axis = 1)

In [ ]:
test.head()

,ID,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,"(administracion de empresas,)","(administracion en salud ocupacional,)","(administracion financiera,)",...,"(medicina,)","(negocios internacionales,)","(otros,)","(psicologia,)","(trabajo social,)",ESTU_PAGOMATRICULAPROPIO_No,ESTU_PAGOMATRICULAPROPIO_Si,ESTU_PAGOMATRICULAPROPIO_no info,FAMI_TIENEINTERNET_No,FAMI_TIENEINTERNET_Si
0,550236,0,2.0,2.0,4.0,9.0,5.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0,1,0,0,1
1,98545,1,5.0,4.0,3.0,7.0,9.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1,0,0,0,1
2,499179,1,4.0,1.0,4.0,6.0,7.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,1,0,0,0,1
3,782980,0,4.0,4.0,2.0,4.0,4.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1,0,0,1,0
4,785185,1,5.0,3.0,3.0,7.0,7.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1,0,0,0,1

In [ ]:
test.shape

(296786, 33)

In [ ]:
test.columns

Index([                                    'ID',
                       'ESTU_PRGM_DEPARTAMENTO',
               'ESTU_VALORMATRICULAUNIVERSIDAD',
                      'ESTU_HORASSEMANATRABAJA',
                         'FAMI_ESTRATOVIVIENDA',
                          'FAMI_EDUCACIONPADRE',
                          'FAMI_EDUCACIONMADRE',
                ('administracion de empresas',),
       ('administracion en salud ocupacional',),
                 ('administracion financiera',),
                              ('arquitectura',),
                       ('comunicacion social',),
                        ('contaduria publica',),
                                   ('derecho',),
                                  ('economia',),
                                ('enfermeria',),
                      ('ingenieria ambiental',),
                          ('ingenieria civil',),
                    ('ingenieria de sistemas',),
                    ('ingenieria electronica',),
                     ('ingenieria industrial',),
                       ('ingenieria mecanica',),
        ('licenciatura en pedagogia infantil',),
                                  ('medicina',),
                  ('negocios internacionales',),
                                     ('otros',),
                                ('psicologia',),
                            ('trabajo social',),
                  'ESTU_PAGOMATRICULAPROPIO_No',
                  'ESTU_PAGOMATRICULAPROPIO_Si',
             'ESTU_PAGOMATRICULAPROPIO_no info',
                        'FAMI_TIENEINTERNET_No',
                        'FAMI_TIENEINTERNET_Si'],
      dtype='object')

In [ ]:
test.to_csv('test2.csv', index = False)

In [ ]:
!head test2.csv

ID,ESTU_PRGM_DEPARTAMENTO,ESTU_VALORMATRICULAUNIVERSIDAD,ESTU_HORASSEMANATRABAJA,FAMI_ESTRATOVIVIENDA,FAMI_EDUCACIONPADRE,FAMI_EDUCACIONMADRE,"('administracion de empresas',)","('administracion en salud ocupacional',)","('administracion financiera',)","('arquitectura',)","('comunicacion social',)","('contaduria publica',)","('derecho',)","('economia',)","('enfermeria',)","('ingenieria ambiental',)","('ingenieria civil',)","('ingenieria de sistemas',)","('ingenieria electronica',)","('ingenieria industrial',)","('ingenieria mecanica',)","('licenciatura en pedagogia infantil',)","('medicina',)","('negocios internacionales',)","('otros',)","('psicologia',)","('trabajo social',)",ESTU_PAGOMATRICULAPROPIO_No,ESTU_PAGOMATRICULAPROPIO_Si,ESTU_PAGOMATRICULAPROPIO_no info,FAMI_TIENEINTERNET_No,FAMI_TIENEINTERNET_Si
550236,0,2.0,2.0,4.0,9.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0,1,0,0,1
98545,1,5.0,4.0,3.0,7.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1,0,0,0,1
499179,1,4.0,1.0,4.0,6.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1,0,0,0,1
782980,0,4.0,4.0,2.0,4.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0,1,0
785185,1,5.0,3.0,3.0,7.0,7.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0,0,1
58495,1,3.0,5.0,2.0,1.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0,1,0,0,1
705444,1,2.0,1.0,4.0,5.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0,0,1
557548,1,8.0,2.0,5.0,12.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0,0,1
519909,1,4.0,4.0,3.0,7.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1,0,0,1,0